name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
    branches: [ main ]
    types: [ ready_for_review ]

jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest 
        - windows-latest 
        - macos-latest
  
    # Run the CI on all three OSes mentionned
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
