name: Create and upload release

on:
  push:
    tags: 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    name: Build and release the .jar file

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Package using Maven
        run: mvn --update-snapshots package -P prod

      - name: Get tag
        id: release-tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Create draft release
        id: create-release
        uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ steps.release-tag.outputs.tag }}
          release_name: <<edit title>>
          body: <<edit body>>
          prerelease: false
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch release version from Maven
        id: local-version
        run: echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Upload generated artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: target/maze-${{ steps.local-version.outputs.version }}.jar
          asset_name: maze-${{ steps.local-version.outputs.version }}.jar
          asset_content_type: application/octet-stream
